// AUTO-GENERATED by generate_das_api_catalog.py — do not edit.
// Source of truth: src/wsl/das/wsl_api_module.cpp (addExtern calls).
#pragma once

#ifndef IN_MODULE_INTERFACE
#include <string>
#endif
#ifndef IN_MODULE_INTERFACE
#include <vector>
#endif

namespace wsl::mcp_server {

struct das_api_entry {
  std::string name;       // Daslang-callable name
  std::string cpp;        // C++ symbol bound via DAS_BIND_FUN
  std::string side_effect; // raw ::das::SideEffects value
  std::string effect;     // read | write | unknown
  std::string category;   // query | mutation | action
  std::vector<std::string> args;
};

inline const std::vector<das_api_entry>& das_api_catalog() {
  static const std::vector<das_api_entry> catalog = {
    {"get_rigid_body_mass", "get_rigid_body_mass", "accessExternal", "read", "query", {"proxy", "at"}},
    {"log_info", "wsl_log_info", "modifyExternal", "write", "action", {"msg"}},
    {"log_debug", "wsl_log_debug", "modifyExternal", "write", "action", {"msg"}},
    {"log_warn", "wsl_log_warn", "modifyExternal", "write", "action", {"msg"}},
    {"log_error", "wsl_log_error", "modifyExternal", "write", "action", {"msg"}},
    {"entity_create", "wsl_entity_create", "modifyExternal", "write", "action", {}},
    {"entity_destroy", "wsl_entity_destroy", "modifyExternal", "write", "action", {}},
    {"entity_valid", "wsl_entity_valid", "accessExternal", "read", "action", {"entity"}},
    {"entity_is_null", "wsl_entity_is_null", "none", "unknown", "action", {"entity"}},
    {"null_entity", "wsl_null_entity", "none", "unknown", "action", {}},
    {"has_component", "wsl_has_component", "accessExternal", "read", "query", {"type_id", "entity"}},
    {"add_component", "wsl_add_component", "modifyExternal", "write", "mutation", {}},
    {"remove_component", "wsl_remove_component", "modifyExternal", "write", "mutation", {}},
    {"find_entity_by_name", "wsl_find_entity_by_name", "accessExternal", "read", "query", {"name"}},
    {"set_entity_name", "wsl_set_entity_name", "modifyExternal", "write", "mutation", {"entity", "name"}},
    {"get_active_camera", "wsl_get_active_camera", "accessExternal", "read", "query", {}},
    {"set_active_camera", "wsl_set_active_camera", "modifyExternal", "write", "mutation", {"entity"}},
    {"instantiate_prefab", "wsl_instantiate_prefab", "modifyExternal", "write", "action", {"path"}},
    {"refresh_editor_viewport", "wsl_refresh_editor_viewport", "modifyExternal", "write", "mutation", {}},
    {"get_editor_img_min_x", "wsl_get_editor_img_min_x", "accessExternal", "read", "query", {}},
    {"get_editor_img_min_y", "wsl_get_editor_img_min_y", "accessExternal", "read", "query", {}},
    {"get_editor_img_size_x", "wsl_get_editor_img_size_x", "accessExternal", "read", "query", {}},
    {"get_editor_img_size_y", "wsl_get_editor_img_size_y", "accessExternal", "read", "query", {}},
    {"TYPE_TRANSFORM", "wsl_type_id_transform", "none", "unknown", "action", {}},
    {"TYPE_CAMERA", "wsl_type_id_camera", "none", "unknown", "action", {}},
    {"TYPE_HIERARCHY", "wsl_type_id_hierarchy", "none", "unknown", "action", {}},
    {"TYPE_WORLD_TRANSFORM", "wsl_type_id_world_transform", "none", "unknown", "action", {}},
    {"TYPE_TRANSFORM_2D", "wsl_type_id_transform_2d", "none", "unknown", "action", {}},
    {"TYPE_CAMERA_2D", "wsl_type_id_camera_2d", "none", "unknown", "action", {}},
    {"TYPE_SPRITE_2D", "wsl_type_id_sprite_2d", "none", "unknown", "action", {}},
    {"TYPE_POINT_LIGHT", "wsl_type_id_point_light", "none", "unknown", "action", {}},
    {"TYPE_DIRECTIONAL_LIGHT", "wsl_type_id_directional_light", "none", "unknown", "action", {}},
    {"TYPE_SPOT_LIGHT", "wsl_type_id_spot_light", "none", "unknown", "action", {}},
    {"TYPE_RIGID_BODY", "wsl_type_id_rigid_body", "none", "unknown", "action", {}},
    {"TYPE_CHARACTER_BODY", "wsl_type_id_character_body", "none", "unknown", "action", {}},
    {"TYPE_MODEL_INSTANCE_3D", "wsl_type_id_model_instance_3d", "none", "unknown", "action", {}},
    {"TYPE_AREA_3D", "wsl_type_id_area_3d", "none", "unknown", "action", {}},
    {"TYPE_AUDIO", "wsl_type_id_audio", "none", "unknown", "action", {}},
    {"TYPE_PREFAB_INSTANCE", "wsl_type_id_prefab_instance", "none", "unknown", "action", {}},
    {"TYPE_SUBVIEWPORT", "wsl_type_id_subviewport", "none", "unknown", "action", {}},
    {"is_key_pressed", "wsl_is_key_pressed", "accessExternal", "read", "query", {"scancode"}},
    {"get_camera_fov", "wsl_get_camera_fov", "accessExternal", "read", "query", {"camera"}},
    {"set_camera_fov", "wsl_set_camera_fov", "modifyExternal", "write", "mutation", {"camera", "fov"}},
    {"get_camera_near", "wsl_get_camera_near", "accessExternal", "read", "query", {"camera"}},
    {"set_camera_near", "wsl_set_camera_near", "modifyExternal", "write", "mutation", {"camera", "near_val"}},
    {"get_camera_far", "wsl_get_camera_far", "accessExternal", "read", "query", {"camera"}},
    {"set_camera_far", "wsl_set_camera_far", "modifyExternal", "write", "mutation", {"camera", "far_val"}},
    {"get_camera_aspect_ratio", "wsl_get_camera_aspect_ratio", "accessExternal", "read", "query", {"camera"}},
    {"set_camera_aspect_ratio", "wsl_set_camera_aspect_ratio", "modifyExternal", "write", "mutation", {"camera", "aspect"}},
    {"set_relative_mouse_mode", "wsl_set_relative_mouse_mode", "modifyExternal", "write", "mutation", {"enabled"}},
    {"cursor_visible", "wsl_cursor_visible", "accessExternal", "read", "action", {}},
    {"show_cursor", "wsl_show_cursor", "modifyExternal", "write", "mutation", {}},
    {"hide_cursor", "wsl_hide_cursor", "modifyExternal", "write", "mutation", {}},
    {"refresh_window_size", "wsl_refresh_window_size", "modifyExternal", "write", "mutation", {}},
    {"get_window_width", "wsl_get_window_width", "accessExternal", "read", "query", {}},
    {"get_window_height", "wsl_get_window_height", "accessExternal", "read", "query", {}},
    {"get_component_type_id", "wsl_get_component_type_id", "accessExternal", "read", "query", {"display_name"}},
    {"each_entity_id_with", "each_entity_id_with", "invoke", "unknown", "action", {"type_ids", "blk", "context", "at"}},
    {"_get_component_type_id_by_name", "wsl_get_component_type_id_by_name", "accessExternal", "read", "action", {"type_name"}},
    {"_get_component_data", "wsl_get_component_data", "accessExternal", "read", "action", {"entity", "type_id"}},
    {"make_pick_ray", "wsl_make_pick_ray", "modifyExternal", "write", "action", {}},
    {"get_ray_origin_x", "wsl_get_ray_origin_x", "accessExternal", "read", "query", {}},
    {"get_ray_origin_y", "wsl_get_ray_origin_y", "accessExternal", "read", "query", {}},
    {"get_ray_origin_z", "wsl_get_ray_origin_z", "accessExternal", "read", "query", {}},
    {"get_ray_dir_x", "wsl_get_ray_dir_x", "accessExternal", "read", "query", {}},
    {"get_ray_dir_y", "wsl_get_ray_dir_y", "accessExternal", "read", "query", {}},
    {"get_ray_dir_z", "wsl_get_ray_dir_z", "accessExternal", "read", "query", {}},
    {"ray_plane_intersect", "wsl_ray_plane_intersect", "modifyExternal", "write", "action", {}},
    {"get_hit_x", "wsl_get_hit_x", "accessExternal", "read", "query", {}},
    {"get_hit_y", "wsl_get_hit_y", "accessExternal", "read", "query", {}},
    {"get_hit_z", "wsl_get_hit_z", "accessExternal", "read", "query", {}},
    {"get_time", "wsl_get_time", "accessExternal", "read", "query", {}},
    {"get_elapsed_time", "wsl_get_elapsed_time", "accessExternal", "read", "query", {}},
    {"apply_impulse", "wsl_apply_impulse", "modifyExternal", "write", "mutation", {"entity", "x", "y", "z"}},
    {"apply_force", "wsl_apply_force", "modifyExternal", "write", "mutation", {"entity", "x", "y", "z"}},
    {"audio_play", "wsl_audio_play", "modifyExternal", "write", "action", {"entity"}},
    {"audio_stop", "wsl_audio_stop", "modifyExternal", "write", "action", {"entity"}},
    {"audio_pause", "wsl_audio_pause", "modifyExternal", "write", "action", {"entity"}},
    {"audio_resume", "wsl_audio_resume", "modifyExternal", "write", "action", {"entity"}},
    {"audio_set_volume", "wsl_audio_set_volume", "modifyExternal", "write", "action", {"entity", "volume"}},
    {"set_system_stage", "wsl_set_system_stage", "modifyExternal", "write", "mutation", {"stage"}},
    {"set_system_dependency", "wsl_set_system_dependency", "modifyExternal", "write", "mutation", {"name"}},
    {"set_system_conflict", "wsl_set_system_conflict", "modifyExternal", "write", "mutation", {"name"}},
    {"event_connect", "wsl_event_connect", "modifyExternal", "write", "action", {"event_name", "system_name", "handler_name"}},
    {"event_disconnect", "wsl_event_disconnect", "modifyExternal", "write", "action", {"event_name", "system_name", "handler_name"}},
    {"event_declare_source", "wsl_event_declare_source", "modifyExternal", "write", "action", {"event_name", "system_name"}},
    {"event_declare_sink", "wsl_event_declare_sink", "modifyExternal", "write", "action", {"event_name", "system_name", "handler_name"}},
    {"set_model", "wsl_set_model", "modifyExternal", "write", "mutation", {"entity", "path"}},
    {"set_model_material_override", "wsl_set_model_material_override", "modifyExternal", "write", "mutation", {"entity", "path"}},
    {"set_model_visibility_range", "wsl_set_model_visibility_range", "modifyExternal", "write", "mutation", {"entity", "range"}},
  };
  return catalog;
}

} // namespace wsl::mcp_server
