#!/usr/bin/env python3
"""Generate an accurate catalog of the weasel Daslang API.

The authoritative registration site is the sequence of `addExtern<>` calls in
wsl_api_module.cpp (Module_WeaselApi). Hand-maintaining a separate list
invariably drifts, so this script parses that file and emits:

  * a C++ header (DAS_API_CATALOG_HPP) containing a static, dependency-free
    catalog of every registered extern, and
  * (optionally) an RST fragment for the Sphinx docs.

Run it whenever the registration site changes; the generated header is the
single source of truth for the `describe_das_api` MCP tool and `das api` CLI.
"""

import argparse
import json
import re
import sys

ADD_EXTERN_RE = re.compile(
    r"addExtern\s*<\s*DAS_BIND_FUN\s*\(\s*([A-Za-z_][\w]*)\s*\)\s*>\s*\("
)
# The Daslang name is the 3rd positional arg: `(*this, lib, "NAME", ...`.
NAME_RE = re.compile(r'\blib,\s*"([^"]+)"')
# Side-effects enum may be on the same or a later line than the name.
SE_RE = re.compile(r"::das::SideEffects::([A-Za-z_][\w]*)")
ARG_RE = re.compile(r'->arg\s*\(\s*"([^"]+)"\s*\)')
ARGS_RE = re.compile(r"->args\s*\(\s*\{([^}]*)\}\s*\)")


def classify(name):
    n = name.lower()
    if n.startswith(
        ("is_", "get_", "has_", "query_", "find_", "count_", "list_", "read_")
    ):
        return "query"
    if n.startswith(
        (
            "set_",
            "add_",
            "remove_",
            "create_",
            "destroy_",
            "delete_",
            "apply_",
            "update_",
            "start_",
            "stop_",
            "enable_",
            "disable_",
            "show_",
            "hide_",
            "load_",
            "unload_",
            "refresh_",
            "reset_",
            "clear_",
            "spawn_",
            "kill_",
            "attach_",
            "detach_",
        )
    ):
        return "mutation"
    return "action"


def side_effect_class(se):
    if se == "accessExternal":
        return "read"
    if se in ("modifyExternal", "modifyArgument"):
        return "write"
    return "unknown"


def parse(path):
    entries = []
    current = None
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            m = ADD_EXTERN_RE.search(line)
            if m:
                current = {
                    "cpp": m.group(1),
                    "name": "",
                    "se": "",
                    "args": [],
                }
            if current is None:
                continue
            nm = NAME_RE.search(line)
            if nm:
                current["name"] = nm.group(1)
            sm = SE_RE.search(line)
            if sm:
                current["se"] = sm.group(1)
            for am in ARG_RE.finditer(line):
                current["args"].append(am.group(1))
            for asm in ARGS_RE.finditer(line):
                for a in re.findall(r'"([^"]+)"', asm.group(1)):
                    current["args"].append(a)
            if ");" in line:
                if current["name"]:
                    current["category"] = classify(current["name"])
                    current["effect"] = side_effect_class(current["se"])
                    entries.append(current)
                current = None
    return entries


def emit_hpp(entries, out):
    out.write("// AUTO-GENERATED by generate_das_api_catalog.py — do not edit.\n")
    out.write("// Source of truth: src/wsl/das/wsl_api_module.cpp (addExtern calls).\n")
    out.write("#pragma once\n\n")
    out.write("#include <string>\n")
    out.write("#include <vector>\n\n")
    out.write("namespace wsl::mcp_server {\n\n")
    out.write("struct das_api_entry {\n")
    out.write("  std::string name;       // Daslang-callable name\n")
    out.write("  std::string cpp;        // C++ symbol bound via DAS_BIND_FUN\n")
    out.write("  std::string side_effect; // raw ::das::SideEffects value\n")
    out.write("  std::string effect;     // read | write | unknown\n")
    out.write("  std::string category;   // query | mutation | action\n")
    out.write("  std::vector<std::string> args;\n")
    out.write("};\n\n")
    out.write("inline const std::vector<das_api_entry>& das_api_catalog() {\n")
    out.write("  static const std::vector<das_api_entry> catalog = {\n")
    for e in entries:
        args = ", ".join('"%s"' % a for a in e["args"])
        out.write(
            '    {"%s", "%s", "%s", "%s", "%s", {%s}},\n'
            % (e["name"], e["cpp"], e["se"], e["effect"], e["category"], args)
        )
    out.write("  };\n")
    out.write("  return catalog;\n")
    out.write("}\n\n")
    out.write("} // namespace wsl::mcp_server\n")


def emit_rst(entries, out):
    out.write(".. _weasel-api:\n\n")
    out.write("Weasel Daslang API\n")
    out.write("==================\n\n")
    out.write("This reference is generated from the runtime registration site\n")
    out.write("(``src/wsl/das/wsl_api_module.cpp``). It lists every function\n")
    out.write("exposed to Daslang; nothing here is hand-written.\n\n")
    by_cat = {}
    for e in entries:
        by_cat.setdefault(e["category"], []).append(e)
    order = ["query", "mutation", "action"]
    for cat in order:
        if cat not in by_cat:
            continue
        out.write("%s\n" % cat.capitalize() + "-" * len(cat) + "\n\n")
        for e in sorted(by_cat[cat], key=lambda x: x["name"]):
            args = ", ".join(e["args"]) if e["args"] else ""
            out.write("- ``%s(%s)`` — *%s*\n" % (e["name"], args, e["effect"]))
        out.write("\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True, help="path to wsl_api_module.cpp")
    ap.add_argument("--hpp", required=True, help="output .hpp path")
    ap.add_argument("--rst", help="optional output .rst path")
    args = ap.parse_args()

    entries = parse(args.source)
    if not entries:
        sys.stderr.write("error: no addExtern entries parsed\n")
        sys.exit(1)

    with open(args.hpp, "w", encoding="utf-8") as fh:
        emit_hpp(entries, fh)
    if args.rst:
        with open(args.rst, "w", encoding="utf-8") as fh:
            emit_rst(entries, fh)

    print("wrote %d api entries to %s" % (len(entries), args.hpp))


if __name__ == "__main__":
    main()
