if(NOT TARGET wsl)
    # Check if a pre-built engine exists (prefer explicit build dir if provided)
    set(_WEASEL_TARGETS_PATH "")
    if(DEFINED Weasel_BUILD_DIR AND EXISTS "${Weasel_BUILD_DIR}/WeaselTargets.cmake")
        set(_WEASEL_TARGETS_PATH "${Weasel_BUILD_DIR}/WeaselTargets.cmake")
    elseif(EXISTS "${CMAKE_CURRENT_LIST_DIR}/build/WeaselTargets.cmake")
        set(_WEASEL_TARGETS_PATH "${CMAKE_CURRENT_LIST_DIR}/build/WeaselTargets.cmake")
    endif()

    if(_WEASEL_TARGETS_PATH)
        message(STATUS "Using pre-built Weasel Engine from: ${_WEASEL_TARGETS_PATH}")
        
        include(CMakeFindDependencyMacro)
        find_dependency(SDL3 CONFIG REQUIRED)
        find_dependency(LibArchive REQUIRED)
        find_dependency(PkgConfig REQUIRED)

        include("${_WEASEL_TARGETS_PATH}")
        if(TARGET Weasel::wsl)
            add_library(wsl ALIAS Weasel::wsl)
            set(Weasel_FOUND TRUE)
            return()
        endif()
    endif()

    # Fallback: add_subdirectory (builds from source)
    message(STATUS "Pre-built Weasel Engine not found, building from source...")
    add_subdirectory("${CMAKE_CURRENT_LIST_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/weasel")
endif()
