module;
// GMF: standard library + third-party
#include <algorithm>
#include <atomic>
#include <cassert>
#include <cmath>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <format>
#include <functional>
#include <fstream>
#include <iostream>
#include <memory>
#include <mutex>
#include <optional>
#include <set>
#include <span>
#include <string>
#include <string_view>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
#include <entt/entt.hpp>
#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <RmlUi/Core.h>
#include <RmlUi_Platform_SDL.h>
// See ui_manager.hpp: RmlUi_Renderer_SDL_GPU.h uses `interface` as a
// parameter name, colliding with the COM macro from windows.h.
#ifdef interface
#pragma push_macro ("interface")
#undef interface
#define WSL_POP_RMLUI_INTERFACE
#endif
#include <RmlUi_Renderer_SDL_GPU.h>
#ifdef WSL_POP_RMLUI_INTERFACE
#pragma pop_macro ("interface")
#undef WSL_POP_RMLUI_INTERFACE
#endif
#include <SDL3/SDL.h>
#include <SDL3/SDL_gpu.h>
#include <SDL3/SDL_events.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/base_sink.h>
#include <tracy/Tracy.hpp>
#include <simdjson.h>
#include <stb_image.h>
#include <archive.h>
#include <fastgltf/core.hpp>
#include <fastgltf/types.hpp>
#include <meshoptimizer.h>
#include <rfl.hpp>
#include <rfl/Result.hpp>
#include <rfl/json.hpp>
#include <rfl/msgpack.hpp>
#include <SDL3_image/SDL_image.h>
#include <SDL3_mixer/SDL_mixer.h>
#include <imgui.h>
#include <imgui_internal.h>
#include <future>
#include <tuple>
#include <setjmp.h>
#include "phys/layers.hpp"

export module wsl.core;
#define IN_MODULE_INTERFACE

// Purview: engine headers (filtered, no serialize/rfl/stb)
#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "app.hpp"
#include "comp/area3d.hpp"
#include "comp/audio.hpp"
#include "comp/camera.hpp"
#include "comp/camera_2d.hpp"
#include "comp/character_body.hpp"
#include "comp/component_meta.hpp"
#include "comp/components.hpp"
#include "comp/directional_light.hpp"
#include "comp/hierarchy.hpp"
#include "comp/model_instance_3d.hpp"
#include "comp/point_light.hpp"
#include "comp/prefab_instance.hpp"
#include "comp/rigid_body.hpp"
#include "comp/singl/editor_context.hpp"
#include "comp/singl/engine_resources.hpp"
#include "comp/singl/physics_manager.hpp"
#include "comp/singl/rendering_manager.hpp"
#include "comp/singl/runtime_context.hpp"
#include "comp/singl/skybox_instance_3d.hpp"
#include "comp/singl/ui_manager.hpp"
#include "comp/spot_light.hpp"
#include "comp/sprite_2d.hpp"
#include "comp/subviewport.hpp"
#include "comp/transform.hpp"
#include "comp/transform_2d.hpp"
#include "comp/world_transform.hpp"
#include "das/das_engine.hpp"
#if WEASEL_HAS_DASLANG
#include "das/das_api_catalog.gen.hpp"
#include "das/das_ecs_binds.hpp"
#include "das/das_interop.hpp"
#include "das/das_system_adapter.hpp"
#include "das/wsl_api_component_accessors.hpp"
#include "das/wsl_api_module.hpp"
#include "das/wsl_event_binds.hpp"
#endif
#include "debug/debug_renderer.hpp"
#include "editor/editor_ui_layer_interface.hpp"
#include "editor_app.hpp"
#include "event.hpp"
#include "event/event_hub.hpp"
#include "event/event_hub_fwd.hpp"
#include "event/message_bus.hpp"
#include "event/message_event.hpp"
#include "events.hpp"
#include "gfx/batch_renderer_2d.hpp"
#include "gfx/clustered_lighting.hpp"
#include "gfx/cubemap.hpp"
#include "gfx/gpu_resources.hpp"
#include "gfx/image.hpp"
#include "gfx/imgui_renderer_interface.hpp"
#include "gfx/lighting.hpp"
#include "gfx/material.hpp"
#include "gfx/material_asset.hpp"
#include "gfx/mesh.hpp"
#include "gfx/model_3d.hpp"
#include "gfx/pipeline_cache.hpp"
#include "gfx/render_context.hpp"
#include "gfx/render_window.hpp"
#include "gfx/renderdoc.hpp"
#include "gfx/renderer.hpp"
#include "gfx/scene_renderer.hpp"
#include "gfx/shader.hpp"
#include "gfx/shader_compiler.hpp"
#include "gfx/shader_graph.hpp"
#include "gfx/shader_graph_codegen.hpp"
#include "gfx/shader_program.hpp"
#include "gfx/subviewport_target.hpp"
#include "gfx/tracy_gpu_mem.hpp"
#include "gfx/ui_render_interface.hpp"
#include "gfx/viewport.hpp"
#include "input.hpp"
#include "log/log.hpp"
#include "log/tracy_sink.hpp"
#include "math/mikktspace.hpp"
#include "net/command_protocol.hpp"
#include "phys/box3d_adapter.hpp"
#include "phys/physics_engine.hpp"
#include "ray.hpp"
#include "reg/component_registry.hpp"
#include "reg/detail/registry_helpers.hpp"
#include "reg/registry_handle.hpp"
#include "reg/registry_queries.hpp"
#include "reg/runtime_project_module.hpp"
#include "reg/singleton_registry.hpp"
#include "reg/system_factory_registry.hpp"
#include "rsc/xmake_file_api.hpp"
#include "rsc/cpu_model.hpp"
#include "rsc/cubemap_loader.hpp"
#include "rsc/image_loader.hpp"
#include "rsc/model_loader.hpp"
#include "rsc/project.hpp"
#include "rsc/project_loader.hpp"
#include "rsc/resource_ids.hpp"
#include "rsc/resource_manager.hpp"
#include "rsc/resource_ref.hpp"
#include "rsc/runtime_project_module.hpp"
#include "rsc/scene.hpp"
#include "rsc/scene_loader.hpp"
#include "rsc/scene_manager.hpp"
#include "rsc/shader_loader.hpp"
#include "rsc/world.hpp"
#include "sys/audio_system.hpp"
#include "sys/core_systems.hpp"
#include "sys/lighting_system.hpp"
#include "sys/physics_system.hpp"
#include "sys/render_2d_system.hpp"
#include "sys/render_3d_system.hpp"
#include "sys/render_frame.hpp"
#include "sys/render_ui_system.hpp"
#include "sys/shadow_system.hpp"
#include "sys/skybox_system.hpp"
#include "sys/stage_registry.hpp"
#include "sys/system.hpp"
#include "sys/system_dependency_graph.hpp"
#include "sys/system_scheduler.hpp"
#include "sys/task_pool.hpp"
#include "sys/tracy_telemetry.hpp"
#include "sys/transform_system.hpp"

using ::RenderInterface_SDL_GPU;
